"""admin and users

Revision ID: 718bb0168657
Revises: 
Create Date: 2026-07-01 10:52:03.892217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718bb0168657'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('primary_domain', sa.String(length=256), nullable=False),
    sa.Column('ldap_google_enabled', sa.Boolean(), nullable=False),
    sa.Column('ldap_ms_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_organization_primary_domain'), ['primary_domain'], unique=False)

    op.create_table('target_system',
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('system_fqdn', sa.String(length=64), nullable=False),
    sa.Column('system_description', sa.String(length=256), nullable=False),
    sa.Column('system_Type', sa.String(length=64), nullable=False),
    sa.Column('system_cert_format', sa.String(length=64), nullable=False),
    sa.Column('system_cert_filename', sa.String(length=256), nullable=False),
    sa.Column('system_cert_path', sa.String(length=256), nullable=False),
    sa.Column('system_key_filename', sa.String(length=256), nullable=False),
    sa.Column('system_last_validated', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('system_id')
    )
    with op.batch_alter_table('target_system', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_target_system_system_Type'), ['system_Type'], unique=False)
        batch_op.create_index(batch_op.f('ix_target_system_system_cert_filename'), ['system_cert_filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_target_system_system_cert_format'), ['system_cert_format'], unique=False)
        batch_op.create_index(batch_op.f('ix_target_system_system_cert_path'), ['system_cert_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_target_system_system_description'), ['system_description'], unique=False)
        batch_op.create_index(batch_op.f('ix_target_system_system_fqdn'), ['system_fqdn'], unique=False)
        batch_op.create_index(batch_op.f('ix_target_system_system_key_filename'), ['system_key_filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_target_system_system_last_validated'), ['system_last_validated'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_username', sa.String(length=64), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('user_fname', sa.String(length=120), nullable=False),
    sa.Column('user_mname', sa.String(length=120), nullable=False),
    sa.Column('user_lname', sa.String(length=120), nullable=False),
    sa.Column('user_displayname', sa.String(length=120), nullable=False),
    sa.Column('user_security_groups', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_user_displayname'), ['user_displayname'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_user_email'), ['user_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_user_fname'), ['user_fname'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_user_lname'), ['user_lname'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_user_mname'), ['user_mname'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_user_security_groups'), ['user_security_groups'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_user_username'), ['user_username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_user_security_groups'))
        batch_op.drop_index(batch_op.f('ix_user_user_mname'))
        batch_op.drop_index(batch_op.f('ix_user_user_lname'))
        batch_op.drop_index(batch_op.f('ix_user_user_fname'))
        batch_op.drop_index(batch_op.f('ix_user_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_user_displayname'))

    op.drop_table('user')
    with op.batch_alter_table('target_system', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_target_system_system_last_validated'))
        batch_op.drop_index(batch_op.f('ix_target_system_system_key_filename'))
        batch_op.drop_index(batch_op.f('ix_target_system_system_fqdn'))
        batch_op.drop_index(batch_op.f('ix_target_system_system_description'))
        batch_op.drop_index(batch_op.f('ix_target_system_system_cert_path'))
        batch_op.drop_index(batch_op.f('ix_target_system_system_cert_format'))
        batch_op.drop_index(batch_op.f('ix_target_system_system_cert_filename'))
        batch_op.drop_index(batch_op.f('ix_target_system_system_Type'))

    op.drop_table('target_system')
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_primary_domain'))
        batch_op.drop_index(batch_op.f('ix_organization_name'))
        batch_op.drop_index(batch_op.f('ix_organization_description'))

    op.drop_table('organization')
    # ### end Alembic commands ###
